[prune]
  go-tests = true
  unused-packages = true

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "https://github.com/fsnotify/fsnotify.git"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "=v0.10.0"

[[constraint]]
  name = "github.com/solo-io/ext-auth-plugins"
  version = "=v0.1.1"

[[constraint]]
  name = "github.com/envoyproxy/go-control-plane"
  version = "=v0.9.0"

[[override]]
  name = "github.com/envoyproxy/protoc-gen-validate"
  revision = "9b492f1473afa33350d86b62c298b45da868a33f"

[[override]]
  name = "go.uber.org/zap"
  version = "=v1.10.0"

[[override]]
  name = "go.uber.org/atomic"
  version = "=v1.3.2"

[[override]]
  name = "github.com/golang/protobuf"
  version = "=v1.2.0"

[[override]]
  name = "gopkg.in/tomb.v1"
  revision = "c131134a1947e9afd9cecfe11f4c6dff0732ae58"

[[override]]
  name = "github.com/hpcloud/tail"
  revision = "a1dbeea552b7c8df4b542c66073e393de198a800"

[[override]]
  name = "github.com/onsi/ginkgo"
  version = "=v1.7.0"

[[override]]
  name = "github.com/onsi/gomega"
  version = "=v1.4.3"

[[override]]
  name = "gopkg.in/yaml.v2"
  version = "=v2.2.1"

[[override]]
  name = "google.golang.org/grpc"
  revision = "168a6198bcb0ef175f7dacec0b8691fc141dc9b8"

[[override]]
  name = "github.com/gogo/googleapis"
  version = "=v1.0.0"

[[override]]
  name = "github.com/pelletier/go-toml"
  version = "=v1.2.0"

[[override]]
  name = "google.golang.org/genproto"
  revision = "02b4e95473316948020af0b7a4f0f22c73929b0e"

[[override]]
  name = "golang.org/x/sys"
  revision = "ac767d655b305d4e9612f5f6e33120b9176c4ad4"

[[override]]
  name = "golang.org/x/net"
  revision = "3f473d35a33aa6fdd203e306dc439b797820e3f1"

[[override]]
  name = "golang.org/x/text"
  revision = "f21a4dfb5e38f5895301dc265a8def02365cc3d0"